export default [

    {
        "_id": "A101",
        "title": "Propulsion Assignment",
        "course": "RS101",
        "description": "example description",
        "points": 100,
        "availableDateMonth": "May",
        "availableDateDay": 6,
        "availableDateYear": 2024,
        "availableDateTime": "12:00am",
        "untilDateMonth": "May",
        "untilDateDay": 20,
        "untilDateYear": 2024,
        "untilDateTime": "12:00am",
        "dueDateMonth": "May",
        "dueDateDay": 15,
        "dueDateYear": 2024,
        "dueDateTime": "12:00am"
    },
    {
        "_id": "A102",
        "title": "Combustion Analysis",
        "course": "RS101",
        "description": "example description",
        "points": 100,
        "availableDateMonth": "May",
        "availableDateDay": 6,
        "availableDateYear": 2024,
        "availableDateTime": "12:00am",
        "untilDateMonth": "May",
        "untilDateDay": 20,
        "untilDateYear": 2024,
        "untilDateTime": "12:00am",
        "dueDateMonth": "May",
        "dueDateDay": 15,
        "dueDateYear": 2024,
        "dueDateTime": "12:00am"
    },
    {
        "_id": "A103",
        "title": "Nozzle Design Project",
        "course": "RS101",
        "description": "example description",
        "points": 100,
        "availableDateMonth": "May",
        "availableDateDay": 6,
        "availableDateYear": 2024,
        "availableDateTime": "12:00am",
        "untilDateMonth": "May",
        "untilDateDay": 20,
        "untilDateYear": 2024,
        "untilDateTime": "12:00am",
        "dueDateMonth": "May",
        "dueDateDay": 15,
        "dueDateYear": 2024,
        "dueDateTime": "12:00am"
    },
    {
        "_id": "A201",
        "title": "Aerodynamics Quiz",
        "course": "RS102",
        "description": "example description",
        "points": 100,
        "availableDateMonth": "May",
        "availableDateDay": 6,
        "availableDateYear": 2024,
        "availableDateTime": "12:00am",
        "untilDateMonth": "May",
        "untilDateDay": 20,
        "untilDateYear": 2024,
        "untilDateTime": "12:00am",
        "dueDateMonth": "May",
        "dueDateDay": 15,
        "dueDateYear": 2024,
        "dueDateTime": "12:00am"
    },
    {
        "_id": "A202",
        "title": "Flow Analysis",
        "course": "RS102",
        "description": "example description",
        "points": 100,
        "availableDateMonth": "May",
        "availableDateDay": 6,
        "availableDateYear": 2024,
        "availableDateTime": "12:00am",
        "untilDateMonth": "May",
        "untilDateDay": 20,
        "untilDateYear": 2024,
        "untilDateTime": "12:00am",
        "dueDateMonth": "May",
        "dueDateDay": 15,
        "dueDateYear": 2024,
        "dueDateTime": "12:00am"
    },
    {
        "_id": "A203",
        "title": "Heating Analysis",
        "course": "RS102",
        "description": "example description",
        "points": 100,
        "availableDateMonth": "May",
        "availableDateDay": 6,
        "availableDateYear": 2024,
        "availableDateTime": "12:00am",
        "untilDateMonth": "May",
        "untilDateDay": 20,
        "untilDateYear": 2024,
        "untilDateTime": "12:00am",
        "dueDateMonth": "May",
        "dueDateDay": 15,
        "dueDateYear": 2024,
        "dueDateTime": "12:00am"
    },
    {
        "_id": "A301",
        "title": "Structural Design Task",
        "course": "RS103",
        "description": "example description",
        "points": 100,
        "availableDateMonth": "May",
        "availableDateDay": 6,
        "availableDateYear": 2024,
        "availableDateTime": "12:00am",
        "untilDateMonth": "May",
        "untilDateDay": 20,
        "untilDateYear": 2024,
        "untilDateTime": "12:00am",
        "dueDateMonth": "May",
        "dueDateDay": 15,
        "dueDateYear": 2024,
        "dueDateTime": "12:00am"
    },
    {
        "_id": "A302",
        "title": "Orbital Calculations",
        "course": "RS103",
        "description": "example description",
        "points": 100,
        "availableDateMonth": "May",
        "availableDateDay": 6,
        "availableDateYear": 2024,
        "availableDateTime": "12:00am",
        "untilDateMonth": "May",
        "untilDateDay": 20,
        "untilDateYear": 2024,
        "untilDateTime": "12:00am",
        "dueDateMonth": "May",
        "dueDateDay": 15,
        "dueDateYear": 2024,
        "dueDateTime": "12:00am"
    },
    {
        "_id": "A303",
        "title": "Systems Engineering Exam",
        "course": "RS103",
        "description": "example description",
        "points": 100,
        "availableDateMonth": "May",
        "availableDateDay": 6,
        "availableDateYear": 2024,
        "availableDateTime": "12:00am",
        "untilDateMonth": "May",
        "untilDateDay": 20,
        "untilDateYear": 2024,
        "untilDateTime": "12:00am",
        "dueDateMonth": "May",
        "dueDateDay": 15,
        "dueDateYear": 2024,
        "dueDateTime": "12:00am"
    }
]